name: asd

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: 'mac'
          - os: windows-2019
            platform: 'win'
          - os: ubuntu-latest
            platform: 'linux'
          - os: ubuntu-18.04
            platform: 'linux'
    runs-on: ${{ matrix.os }}
    env:
      npm_config_disturl: https://electronjs.org/headers
      npm_config_target: 15.4.1
      npm_config_runtime: "electron"
     
    steps:
      - name: Set git config
        run: |
          git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Install
        run: |
          yarn install
          node scripts/download-pandoc.js

      - name: Build
        run: |
          yarn build

      - name: Electron-Win
        if: matrix.platform == 'win'
        run: |
          yarn run electron-builder --${{ matrix.platform }} -p never | sed 's/identityName=.*$//'
          if (!(Test-Path out/win-unpacked/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)) { throw 'node-pty not exist' }

